---
title: "Cardiovascular Disease Distributions"
author: "Kelsey Sanchez"
date: "`r Sys.Date()`"
output: pdf_document
---



```{r libraries, include=FALSE}

#All libraries are listed up top; authentication for BQ will be necessary.
#Functions used included before the start of the analysis .



rm(list = ls())
library(bigrquery)
library(foreach)
library(stringr)
#library(plyr)
#library(expss) ###to add labels
library(epiDisplay) ##recommended applied here crosstable, tab1
library(gmodels) ##recommended
library(magrittr)
library(arsenal)
library(gtsummary)
library(rio)



library(ggplot2)
library(gridExtra)
library(scales)
library(gt)
#install(tinytex)
library(tinytex)
library(data.table) ###to write or read and data management 
library(tidyverse) ###for data management
library(dplyr) ###data management
library(reshape)  ###to work on transition from long to wide or wide to long data
library(listr) ###to work on a list of vector, files or..
library(sqldf) ##sql
library(lubridate) ###date time
library(stringr) ###to work on patterns, charaters
library(kableExtra)


options(tinytex.verbose = TRUE)

bq_auth()

```


```{r M1merge, include=FALSE}

#Data Dictionary for column names
dictionary <- rio::import("https://episphere.github.io/conceptGithubActions/aggregate.json",format = "json")
dd <- dplyr::bind_rows(dictionary,.id="CID")
dd <-rbindlist(dictionary,fill=TRUE,use.names=TRUE,idcol="CID")
dd$`Variable Label`[is.na(dd$`Variable Label`)] <- replace_na(dd$'Variable Name')
dd <- as.data.frame.matrix(do.call("rbind",dictionary)) 
dd$CID <- rownames(dd)
#https://shaivyakodan.medium.com/7-useful-r-packages-for-analysis-7f60d28dca98
devtools::install_github("tidyverse/reprex")





## BQ Pull from the participants table just to use for versioning
project <- "nih-nci-dceg-connect-prod-6d04"
billing <- "nih-nci-dceg-connect-prod-6d04" 
recr_M1 <- bq_project_query(project, query="SELECT token,Connect_ID, d_821247024, d_914594314,  d_827220437,d_512820379,
                            d_949302066 , d_517311251  FROM  `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` WHERE  d_821247024='197316935' and d_949302066 ='231311385'")
recr_m1 <- bq_table_download(recr_M1,bigint = "integer64")
cnames <- names(recr_m1)
# Check that it doesn't match any non-number
numbers_only <- function(x) !grepl("\\D", x)
# to check variables in recr_noinact_wl1
for (i in 1: length(cnames)){
  varname <- cnames[i]
  var<-pull(recr_m1,varname)
  recr_m1[,cnames[i]] <- ifelse(numbers_only(var), as.numeric(as.character(var)), var)
}




#### Handling participants that somehow completed both Mod1 version 1 and Mod1 version 2

sql_M1_1 <- bq_project_query(project, query = "SELECT * FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.module1_v1` WHERE Connect_ID IS NOT NULL")
sql_M1_2 <- bq_project_query(project, query = "SELECT * FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.module1_v2` WHERE Connect_ID IS NOT NULL")

M1_V1 <- bq_table_download(sql_M1_1, bigint = "integer64")
M1_V2 <- bq_table_download(sql_M1_2, bigint = "integer64")

# Select matching column names
M1_V1_vars <- colnames(M1_V1)
M1_V2_vars <- colnames(M1_V2)
common_vars <- intersect(M1_V1_vars, M1_V2_vars)

# Subset to common columns
M1_V1_common <- M1_V1[, common_vars]
M1_V2_common <- M1_V2[, common_vars]

# Add version indicator
M1_V1_common$version <- 1
M1_V2_common$version <- 2

# Identify columns with mismatched types
mismatched_cols <- names(M1_V1_common)[sapply(names(M1_V1_common), function(col) {
  class(M1_V1_common[[col]]) != class(M1_V2_common[[col]])
})]

# Convert mismatched columns to character for consistency
M1_V1_common <- M1_V1_common %>%
  mutate(across(all_of(mismatched_cols), as.character))
M1_V2_common <- M1_V2_common %>%
  mutate(across(all_of(mismatched_cols), as.character))

# Combine both versions for participants who completed both
M1_common <- bind_rows(M1_V1_common, M1_V2_common) %>%
  arrange(Connect_ID, desc(version))

# For columns unique to each version
V1_only_vars <- setdiff(M1_V1_vars, common_vars)
V2_only_vars <- setdiff(M1_V2_vars, common_vars)

# Subset each version for unique columns and add version indicator
m1_v1_only <- M1_V1[, c("Connect_ID", V1_only_vars)] %>%
  mutate(version = 1)
m1_v2_only <- M1_V2[, c("Connect_ID", V2_only_vars)] %>%
  mutate(version = 2)

# Combine the unique and common data

M1_common$Connect_ID <- as.numeric(M1_common$Connect_ID)
m1_v1_only$Connect_ID <- as.numeric(m1_v1_only$Connect_ID)
m1_v2_only$Connect_ID <- as.numeric(m1_v2_only$Connect_ID)

m1_common_v1 <- left_join(M1_common, m1_v1_only, by = c("Connect_ID", "version"))

m1_common_v1$Connect_ID <- as.numeric(m1_common_v1$Connect_ID)
m1_combined_v1v2 <- left_join(m1_common_v1, m1_v2_only, by = c("Connect_ID", "version"))

# Filter for complete cases where specific completion criteria are met
m1_complete <- m1_combined_v1v2 %>%
  filter(Connect_ID %in% recr_m1$Connect_ID[recr_m1$d_949302066 == 231311385]) %>%
  arrange(desc(version))

# Remove duplicates, keeping only the most recent version for each Connect_ID
m1_complete_nodup <- m1_complete[!duplicated(m1_complete$Connect_ID),]

m1_complete_nodup$Connect_ID <- as.numeric(m1_complete_nodup$Connect_ID)


### Define requirements of the data: active or passive,  user profile done, consented, mod1 done, verified
parts <- "SELECT Connect_ID, token, d_564964481,d_795827569, d_544150384, d_827220437
FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` 
where Connect_ID IS NOT NULL and (d_512820379='486306141' OR d_512820379='854703046') and d_821247024='197316935' and
(d_919254129='353358909') and (d_699625233='353358909') and (d_949302066='231311385')"
parts_table <- bq_project_query(project, parts)
parts_data <- bq_table_download(parts_table, bigint = "integer64")

parts_data$Connect_ID <- as.numeric(parts_data$Connect_ID) ###need to convert type- m1... is double and parts is character

module1= left_join(parts_data, m1_complete_nodup, by="Connect_ID") 
dim(module1)

```


```{r counts, warning=FALSE, echo=FALSE}

cat("Participants with Module 1 Completion:", dim(module1)[[1]])


data_tib_m1 <- as_tibble(module1)
#dim(module1)

knitr::opts_chunk$set(comment = NA)



```


```{r MhGroup1, warning=FALSE, echo=FALSE, message=FALSE}

knitr::opts_chunk$set(dev = "png", fig.path = "")
                      
                      
mhgroup1COUNT <- data_tib_m1 %>%
  mutate(
    `B12 Deficiency` = if_else(D_167101091_D_698944820 == 1, 1, 0),
    `Coronary Artery` = if_else(D_167101091_D_838744325 == 1, 1, 0),
    `Congestive Heart Failure` = if_else(D_167101091_D_769790179 == 1, 1, 0),
    `High Cholesterol` = if_else(D_167101091_D_699553344 == 1, 1, 0),
    `Heart Attack` = if_else(D_167101091_D_700811160 == 1, 1, 0),
    `Abnormal Heart Rhythm` = if_else(D_167101091_D_336505365 == 1, 1, 0),
    `Chest Pain` = if_else(D_167101091_D_132548932 == 1, 1, 0),
    `Heart Valve Problems` = if_else(D_167101091_D_747787163 == 1, 1, 0),
    `High Blood Pressure` = if_else(D_167101091_D_693851465 == 1, 1, 0),
    `Blood Clots` = if_else(D_167101091_D_512012656 == 1, 1, 0),
    Stroke = if_else(D_167101091_D_619337095 == 1, 1, 0),
    None = if_else(D_167101091_D_535003378 == 1, 1, 0),
    Skipped = if_else(rowSums(select(., starts_with("D_167101091_D_")) == 0 | is.na(select(., starts_with("D_167101091_D_")))) == ncol(select(., starts_with("D_167101091_D_"))), 1, 0)
  )

pivot_data <- mhgroup1COUNT %>%
  select(`B12 Deficiency`:Skipped) %>%
  pivot_longer(cols = everything(), names_to = "Condition", values_to = "Selected") %>%
  filter(Selected == 1) %>%
  group_by(Condition) %>%
  summarise(Frequency = n()) %>%
  ungroup() %>%
  mutate(Percentage = 100 * Frequency / sum(Frequency))


library(ggplot2)
library(scales)
library(dplyr)

bar_funct <- function(data, Title, Xlab, Ylab) {
  data <- data %>% arrange(desc(Frequency))  # ensure descending order
  data$Condition <- factor(data$Condition, levels = data$Condition)  # preserve order in plot
  data$Percentage <- round(data$Percentage, digits=1)

  ggplot(data, aes(x = Condition, y = Frequency)) +
    geom_bar(stat = "identity", fill = "#69b3a2", color = "black") +
    geom_text(aes(label = Percentage), 
              vjust = -0.3, 
              color = "#CC7D15", 
              size = 4, 
              fontface = "bold") +
    xlab(Xlab) +
    ylab(Ylab) +
    ggtitle(Title) +
    scale_y_continuous(breaks = pretty_breaks()) +
    theme_minimal(base_size = 12) +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.text.x = element_text(angle = 45, hjust = 1),
      plot.title = element_text(hjust = 0.5)
    )
}

bar_funct(pivot_data, 'Distribution of Connect Participants Cardiovascular Diseases', 'Disease', 'Count')

```
