default:
  report_maintainer: "Kelsey Dowling"
  pipeline_maintainer: "Jake Peters"
  bucket: "ccc_weekly_metrics_report"
  test_box_folders: 
    - "222593912729"
  gcp_info:
    cloud_build_trigger: ccc-module-metrics
    cloud_run: ccc-module-metrics-api

weekly_module_metrics:
  r_file_name: "CCC Weekly Module Metrics_RMD.Rmd"
  report_file_name: "CCC_Weekly_Module_Metrics.pdf"
  box_folders:
    - "251929835507" # internal
  gcp_info:
    cloud_scheduler: ccc-weekly-module-metrics
    frequency: "0 11 * * 1" # every Monday at 11 AM"

mod1_stats:
  r_file_name: "Merged Module 1 Summary Statistics.Rmd"
  report_file_name: "Merged_Module_1_Summary_Statistics.pdf"
  box_folders:
    - "251314285484"
  gcp_info:
    cloud_scheduler: ccc-module1-statistics
    frequency: "30 11 1 * *" # first of the month at 11:30 AM

mod2_stats:
  r_file_name: "Merged Module 2 Summary Statistics.Rmd"
  report_file_name: "Merged_Module_2_Summary_Statistics.pdf"
  box_folders:
    - "251314285484"
  gcp_info:
    cloud_scheduler: ccc-module2-statistics
    frequency: "0 12 1 * *" # first of the month at 12 PM
    
mod2_qc_metrics:
  r_file_name: "Module_2_Custom_QC.Rmd"
  report_file_name: "Module_2_Custom_QC.pdf"
  box_folders:
    - "211160736918"
  gcp_info:
    cloud_scheduler: ccc-mod2-qc-metrics
    frequency: "15 14 * * 1" 

mod3_qc_metrics:
  r_file_name: "Module_3_Custom_QC.Rmd"
  report_file_name: "Module_3_Custom_QC.pdf"
  box_folders:
    - "226704654836"
  gcp_info:
    cloud_scheduler: ccc-module3-qc-metrics
    frequency: "45 14 1 * *" # first of the month at 12:30 PM
    
mod3_stats:
  r_file_name: "Module 3 Summary Statatistics.Rmd"
  report_file_name: "Module_3_Summary_Statatistics.pdf"
  box_folders:
    - "251314285484"
  gcp_info:
    cloud_scheduler: ccc-module3-statistics
    frequency: "30 12 1 * *" # first of the month at 12:30 PM

mod4_stats:
  r_file_name: "Module 4 Missingness Analysis.Rmd"
  report_file_name: "Module_4_Missingness_Analysis.pdf"
  box_folders:
    - "251314285484"
  gcp_info:
    cloud_scheduler: ccc-module4-statistics
    frequency: "0 13 1 * *" # first of the month at 1 PM

monthly_derived_vars:
  r_file_name: "Monthly Derived Survey Variables.Rmd"
  report_file_name: "Monthly_Derived_Survey_Variables.pdf"
  box_folders:
    - "251314285484"
  gcp_info:
    cloud_scheduler: ccc-monthly-derived-variables
    frequency: "30 13 1 * *" # first of the month at 1:30 PM
    
module1_qc_metrics:
  r_file_name: "Module 1 Custom QC Rule Errors.Rmd"
  report_file_name: "Module_1_Custom_QC_Rule_Errors.pdf"
  box_folders:
    - "203464977998" # internal
  gcp_info:
    cloud_scheduler: ccc-module1-qc-metrics
    frequency: "45 13 * * 1" # every Monday 
    
qol_stats:
  r_file_name: "3 Month Quality of Life Survey Summary Statistics.Rmd"
  report_file_name: "3_Month_Quality_of_Life_Survey_Summary_Statistics.pdf"
  box_folders:
    - "251314285484" # internal
  gcp_info:
    cloud_scheduler: ccc-qol-statistics
    frequency: "00 14 * * 1" 

recruitment_qc_metrics:
  r_file_name: "Rectruitment Derived Variable QC.Rmd"
  report_file_name: "Rectruitment_Derived_Variable_QC.pdf"
  box_folders:
    - "194196493018" # internal
  gcp_info:
    cloud_scheduler: ccc-recruitment-qc-metrics
    frequency: "30 13 * * 1" # every Monday at 1:30 PM"

notifications_qc_metrics:
  r_file_name: "Notifications QC.Rmd"
  report_file_name: "Notifications_QC.pdf"
  box_folders:
    - "255743123858"
  gcp_info:
    cloud_scheduler: ccc-notifications-qc-metrics
    frequency: "30 13 * * 1" # every Monday at 1:30 PM"
    
data_destruction_qc_metrics:
  r_file_name: "Data Destruction CSV Output.R"
  report_file_name: "Data_Destruction_CSV_Output.pdf"
  box_folders:
    - "255783409227"
  gcp_info:
    cloud_scheduler: ccc-data-destruction-qc-metrics
    frequency: "30 13 * * 1" 
    
promis_notification_metrics:
  r_file_name: "PROMIS Completion vs Notifications.Rmd"
  report_file_name: "PROMIS_Completion_vs_Notifications.pdf"
  box_folders:
    - "262287498430"
  gcp_info:
    cloud_scheduler: ccc-promis-notification-metrics
    frequency: "45 13 * * 1" 
    
rca_metrics:
  r_file_name: "RCA Metrics.Rmd"
  report_file_name: "RCA_Metrics.pdf"
  box_folders:
    - "301667614883?s=f4pgipyxybokb3xpduvtd726o6g15fbh"
  gcp_info:
    cloud_scheduler: ccc-rca-metrics
    frequency: "00 14 * * 1" 
    
rca_qc_metrics:
  r_file_name: "RCA Custom QC.Rmd"
  report_file_name: "RCA_Custom_QC.pdf"
  box_folders:
    - "236420612811"
  gcp_info:
    cloud_scheduler: ccc-rca-qc-metrics
    frequency: "30 14 * * 1"
    
csh_metrics:
  r_file_name: "Cancer Screening Summary Statistics.Rmd"
  report_file_name: "Cancer_Screening_History_Metrics.pdf"
  box_folders:
    - "251314285484"
  gcp_info:
    cloud_scheduler: ccc-cancer-screening-history-metrics
    frequency: "30 14 * * 1"
