---
title: "Distributions of Demographics"
author: "Kelsey Sanchez"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r libraries, include=FALSE}


#  pdf-engine: xelatex
#tinytex::install_tinytex()

library(bigrquery)
library(epiDisplay) ##recommended applied here crosstable, tab1
library(gmodels) ##recommended
library(arsenal)
library(gtsummary)
library(rio)



library(ggplot2)
library(gridExtra)
library(scales)
library(gt)
library(tinytex)
library(data.table) ###to write or read and data management 
library(tidyverse) ###for data management
library(dplyr) ###data management
library(lubridate) ###date time
library(stringr) ###to work on patterns, charaters
options(tinytex.verbose = TRUE)

bq_auth()
```


```{r BaseGroup, include=FALSE, warning=FALSE}

project <- "nih-nci-dceg-connect-prod-6d04"

all_ver <- "SELECT Connect_ID, token, state_d_934298480, d_564964481, d_795827569, d_544150384, d_827220437, state_d_706256705, state_d_435027713, state_d_684926335,state_d_849518448,state_d_119643471,state_d_253532712, d_914594314, d_878865966
FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` where Connect_ID IS NOT NULL and d_821247024='197316935' and (d_512820379='486306141' OR d_512820379='854703046')" 


all_ver_table <- bq_project_query(project, all_ver)
all_ver_data <- bq_table_download(all_ver_table, bigint = "integer64",n_max = Inf, page_size = 10000)

all_ver_data$Connect_ID <- as.numeric(all_ver_data$Connect_ID)
```


```{r, include=FALSE, warning=FALSE}

currentDate <- as.Date(Sys.Date(), format='%y/%m/%d')
### 10/11/2023 was the date the new age ranges were added


total_ver <- all_ver_data %>%  
  mutate(site = case_when(d_827220437 == '472940358' ~ "BSWH",
                          d_827220437 == '531629870' ~ "HP",
                          d_827220437 == '548392715' ~ "HFH",
                          d_827220437 == '303349821' ~ "MF",
                          d_827220437 == '657167265' ~ "SH",
                          d_827220437 == '809703864' ~ "UC",
                          d_827220437 == '125001209' ~ "KPCO",
                          d_827220437 == '327912200' ~ "KPGA",
                          d_827220437 == '452412599' ~ "KPNW",
                          d_827220437 == '300267574' ~ "KPHI"),
         age_range = case_when(state_d_934298480 == "713781738"~ "30-34",
                         state_d_934298480 == '631272782' ~ "35-39",
                         state_d_934298480 == '124276120' ~ "40-45",
                         state_d_934298480 == '450985724' ~ "46-50",
                         state_d_934298480 == '363147933' ~ "51-55",
                         state_d_934298480 == '636706443' ~ "56-60",
                         state_d_934298480 == '771230670' ~ "61-65",
                         state_d_934298480 == '722846087' ~ "66-70"),
         site_race = case_when(state_d_684926335 == '635279662' |state_d_849518448 == '768826601' | state_d_119643471 == '635279662' | state_d_253532712=='723775357' ~ "White, Non-Hispanic" , 
                          state_d_684926335 %in% c('232334767', '401335456') |
                            state_d_849518448 == '181769837' |
                            state_d_253532712 %in% c('153444133','572474909','308427446','211228524','277568192','611398522','181769837') |
                            state_d_119643471 %in% c( '232334767','211228524','308427446','432722256','232663805','785578696','200929978','490725843','965998904') ~ "Other",
                          state_d_684926335 == '178420302'  | 
                            state_d_849518448 == '178420302' | 
                            state_d_253532712 == '178420302' |
                            state_d_119643471  %in% c( '986445321','746038746','178420302') |
                            (is.na(state_d_119643471) & d_827220437 == '657167265') ~ "Unknown"),
         site_sex = case_when(state_d_706256705 == '536341288' | state_d_435027713 == '536341288' ~ "Female",
                         state_d_706256705 == '654207589' | state_d_435027713 == '654207589' ~ "Male",
                         #state_d_706256705 == '830573274' ~ "Intersex or Other", # too small of a count for now, need to combine with unknown 
                         state_d_706256705 == '830573274' | state_d_706256705 == '178420302' | state_d_435027713 == '178420302' ~ "Unknown"),
         DOB= as.Date(paste0(d_544150384, "-", d_564964481, "-", d_795827569)),
         age_at_verif= round(time_length(difftime(as.Date(d_914594314), DOB), "years"), digit=0),
         age_now= round(time_length(difftime(currentDate, DOB), "years"), digit=0))


sample <- total_ver %>%  filter(d_878865966=="353358909")

         
```

# Distribution of Age at Verification
## Before Age Expansion
```{r age_before, warning=FALSE, echo=FALSE, message=FALSE}


total_ver %>% mutate(age_at_verif=as.numeric(age_at_verif)) %>%
    filter(!is.na(age_at_verif) & as.Date(d_914594314) < "2023-10-11") %>%
    ggplot(aes(x=age_at_verif))+
     xlab("Age") + ylab("Count") + geom_histogram(color="black", fill = "#164C71")+  ggtitle("Distrbution of Age at Verification using Concatenated DOB")+
  scale_y_continuous(breaks = scales::pretty_breaks(), expand = c(0, 0)) +
  scale_x_continuous(breaks = scales::pretty_breaks(), expand = c(0, 0)) +
    geom_vline(aes(xintercept=mean(age_at_verif, na.rm=T)), colour="#FDBE19", linetype="solid") + 
   theme(
    panel.border = element_blank(),  
         # Remove panel grid lines
         panel.grid.major = element_blank(),
         panel.grid.minor = element_blank(),
         # Remove panel background
         panel.background = element_blank(),
         # Add axis line
         axis.line = element_line(colour = "#BBBEC1")
  )




total_ver %>% 
    filter(!is.na(age_range) & as.Date(d_914594314) < "2023-10-11") %>%
    ggplot(aes(x=age_range))+
     xlab("Age Ranges") + ylab("Count") + geom_bar(color="black", fill = "#164C71")+  ggtitle("Distrbution of Age at Verification using User Profile Age Categories")+
   theme(
    panel.border = element_blank(),  
         # Remove panel grid lines
         panel.grid.major = element_blank(),
         panel.grid.minor = element_blank(),
         # Remove panel background
         panel.background = element_blank(),
         # Add axis line
         axis.line = element_line(colour = "#BBBEC1")
  )

```

## After Age Expansion
```{r age_after, warning=FALSE, echo=FALSE, message=FALSE}

total_ver %>% mutate(age_at_verif=as.numeric(age_at_verif)) %>%
    filter(!is.na(age_at_verif) & as.Date(d_914594314) >= "2023-10-11") %>%
    ggplot(aes(x=age_at_verif))+
     xlab("Age") + ylab("Count") + geom_histogram(color="black", fill = "#164C71")+  ggtitle("Distrbution of Age at Verification using Concatenated DOB \n")+
  scale_y_continuous(breaks = scales::pretty_breaks(), expand = c(0, 0)) +
  scale_x_continuous(breaks = scales::pretty_breaks(), expand = c(0, 0)) +
    geom_vline(aes(xintercept=mean(age_at_verif, na.rm=T)), colour="#FDBE19", linetype="solid") + 
   theme(
    panel.border = element_blank(),  
         # Remove panel grid lines
         panel.grid.major = element_blank(),
         panel.grid.minor = element_blank(),
         # Remove panel background
         panel.background = element_blank(),
         # Add axis line
         axis.line = element_line(colour = "#BBBEC1")
  )



total_ver %>% 
    filter(!is.na(age_range) & as.Date(d_914594314) >= "2023-10-11") %>%
    ggplot(aes(x=age_range))+
     xlab("Age Ranges") + ylab("Count") + geom_bar(color="black", fill = "#164C71")+  ggtitle("Distrbution of Age at Verification using User Profile Age Categories \n")+
   theme(
    panel.border = element_blank(),  
         # Remove panel grid lines
         panel.grid.major = element_blank(),
         panel.grid.minor = element_blank(),
         # Remove panel background
         panel.background = element_blank(),
         # Add axis line
         axis.line = element_line(colour = "#BBBEC1")
  )


```

```{r m1, include=FALSE, warning=FALSE}

dictionary <- rio::import("https://episphere.github.io/conceptGithubActions/aggregate.json",format = "json")
dd <- dplyr::bind_rows(dictionary,.id="CID")
dd <-rbindlist(dictionary,fill=TRUE,use.names=TRUE,idcol="CID")
dd$`Variable Label`[is.na(dd$`Variable Label`)] <- replace_na(dd$'Variable Name')

dd <- as.data.frame.matrix(do.call("rbind",dictionary)) 
dd$CID <- rownames(dd)
#https://shaivyakodan.medium.com/7-useful-r-packages-for-analysis-7f60d28dca98
#devtools::install_github("tidyverse/reprex")

billing <- "nih-nci-dceg-connect-prod-6d04" ##project and billing should be consistent
##517311251 Date/time Status of Completion of Background and Overall Health                         SrvBOH_TmComplete_v1r0
##949302066 Flag for Baseline Module Background and Overall Health                        SrvBOH_BaseStatus_v1r0
recr_M1 <- bq_project_query(project, query="SELECT token,Connect_ID, d_821247024, d_914594314,  d_827220437,d_512820379,
                            d_949302066 , d_517311251  FROM  `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` WHERE  d_821247024='197316935'")
recr_m1 <- bq_table_download(recr_M1,bigint = "integer64",n_max = Inf, page_size = 10000)
cnames <- names(recr_m1)
# Check that it doesn't match any non-number
numbers_only <- function(x) !grepl("\\D", x)
# to check variables in recr_noinact_wl1
for (i in 1: length(cnames)){
  varname <- cnames[i]
  var<-pull(recr_m1,varname)
  recr_m1[,cnames[i]] <- ifelse(numbers_only(var), as.numeric(as.character(var)), var)
}

sql_M1_1 <- bq_project_query(project, query="SELECT Connect_ID, D_384191091_D_384191091_D_583826374,D_384191091_D_384191091_D_636411467,D_384191091_D_384191091_D_458435048,D_384191091_D_384191091_D_706998638,
D_384191091_D_384191091_D_973565052,D_384191091_D_384191091_D_586825330,D_384191091_D_384191091_D_412790539,D_384191091_D_384191091_D_807835037,D_384191091_D_747350323,D_384191091_D_384191091_D_746038746, D_407056417 FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.module1_v1_JP` where Connect_ID is not null")
sql_M1_2 <- bq_project_query(project, query="SELECT Connect_ID, D_384191091_D_384191091_D_583826374,D_384191091_D_384191091_D_636411467,D_384191091_D_384191091_D_458435048,D_384191091_D_384191091_D_706998638,
D_384191091_D_384191091_D_973565052,D_384191091_D_384191091_D_586825330,D_384191091_D_384191091_D_412790539,D_384191091_D_384191091_D_807835037,D_384191091_D_747350323,D_384191091_D_384191091_D_746038746, D_407056417 FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.module1_v2_JP` where Connect_ID is not null")


M1_V1 <- bq_table_download(sql_M1_1,bigint = "integer64",n_max = Inf) #1436 #1436 vars: 1507 01112023 
M1_V2 <- bq_table_download(sql_M1_2,bigint = "integer64",n_max = Inf) #2333 #3033 01112023 var:1531 #6339 obs 1893 vars 05022023

mod1_v1 <- M1_V1
cnames <- names(M1_V1)
###to check variables and convert to numeric
for (i in 1: length(cnames)){
  varname <- cnames[i]
  var<-pull(mod1_v1,varname)
  mod1_v1[,cnames[i]] <- ifelse(numbers_only(var), as.numeric(as.character(var)), var)
}
mod1_v2 <- M1_V2
cnames <- names(M1_V2)
###to check variables and convert to numeric
for (i in 1: length(cnames)){
  varname <- cnames[i]
  var<-pull(mod1_v2,varname)
  mod1_v2[,cnames[i]] <- ifelse(numbers_only(var), as.numeric(as.character(var)), var)
}

M1_V1.var <- colnames(M1_V1)
M1_V2.var <- colnames(M1_V2)
var.matched <- M1_V1.var[which(M1_V1.var %in% M1_V2.var)]
length(var.matched)  #1275 #1278 vars 01112023 #1348 vars 05022023

V1_only_vars <- colnames(M1_V1)[colnames(M1_V1) %nin% var.matched] #232 #229 01112023 #159 05022023
V2_only_vars <- colnames(M1_V2)[colnames(M1_V2) %nin% var.matched] #253 #253 01112023 #545 05022023

length(M1_V1$Connect_ID[M1_V1$Connect_ID %in% M1_V2$Connect_ID])
#[1] 59 with the completion of two versions of Module1 
#[1] 62 with completing both versions of M1 ###double checked 03/28/2023
#68 double checked 05/02/2023

common.IDs <- M1_V1$Connect_ID[M1_V1$Connect_ID %in% M1_V2$Connect_ID]
M1_V1_common <- mod1_v1[,var.matched]

M1_V2_common <- mod1_v2[,var.matched]
M1_V1_common$version <- 1
M1_V2_common$version <- 2

##to check the completion of M1 among these duplicates
partM1_dups <- recr_m1[which(recr_m1$Connect_ID %in% common.IDs),]
table(partM1_dups$d_949302066)

M1_common  <- rbind(M1_V1_common, M1_V2_common) #including 136 duplicates (version 1 and version 2) from 68 participants 05022023
#M1_response <- matrix(data=NA, nrow=118, ncol=967)

m1_v1_only <- mod1_v1[,c("Connect_ID", V1_only_vars)] #230 vars 03282023 #160 vars 05/02/2023
m1_v2_only <- mod1_v2[,c("Connect_ID", V2_only_vars)] #255 vars 03282023 #546 vars 05/02/2023
m1_v1_only$version <- 1
m1_v2_only$version <- 2
#for (i in 1:length)
##to check the completion in each version
length(recr_m1$Connect_ID[which(recr_m1$Connect_ID %in% m1_v1_only$Connect_ID & recr_m1$d_949302066 ==231311385)]) #1364 03282023 # 1370 05022023
length(recr_m1$Connect_ID[which(recr_m1$Connect_ID %in% m1_v2_only$Connect_ID & recr_m1$d_949302066 ==231311385)]) #4870 03282023 # 5731 05022023

#library(janitor)

m1_common <- rbind(M1_V1_common,M1_V2_common)
m1_common_v1 <- base::merge(m1_common, m1_v1_only, by=c("Connect_ID","version"),all.x=TRUE)
m1_combined_v1v2 <- base::merge(m1_common_v1,m1_v2_only,by=c("Connect_ID","version"),all.x=TRUE)
m1_complete <- m1_combined_v1v2[which(m1_combined_v1v2$Connect_ID %in% recr_m1$Connect_ID[which(recr_m1$d_949302066 ==231311385 )]),] #7289 including duplicates 05022023

m1_complete <- m1_complete %>% arrange(desc(version)) 


m1_complete_nodup <- m1_complete[!duplicated(m1_complete$Connect_ID),] 
table(m1_complete_nodup$version)



demos= left_join(m1_complete_nodup, sample, by="Connect_ID")
dim(demos)


demo_tib <- as_tibble(demos)


knitr::opts_chunk$set(comment = NA)

```

# Distrubution of Demographic Factors Among participants with a Blood Sample

## Age
```{r Age_blood, warning=FALSE, echo=FALSE, message=FALSE}
sample %>% 
    filter(!is.na(age_range)) %>%
    ggplot(aes(x=age_range))+
     xlab("Age Ranges") + ylab("Count") + geom_bar(color="black", fill = "#164C71")+  ggtitle("Distrbution of Participant Age Today Among those with a Blood Sample \n")+
   theme(
    panel.border = element_blank(),  
         # Remove panel grid lines
         panel.grid.major = element_blank(),
         panel.grid.minor = element_blank(),
         # Remove panel background
         panel.background = element_blank(),
         # Add axis line
         axis.line = element_line(colour = "#BBBEC1")
  )

# sample %>% mutate(age_now=as.numeric(age_now)) %>%
#     filter(!is.na(age_now)) %>%
#     ggplot(aes(x=age_now))+
#      xlab("Age") + ylab("Count") + geom_histogram(color="black", fill = "#164C71")+  ggtitle("Distrbution of Participant Age Today \n Among those with a Blood Sample")+
#   scale_y_continuous(breaks = scales::pretty_breaks(), expand = c(0, 0)) +
#   scale_x_continuous(breaks = scales::pretty_breaks(), expand = c(0, 0)) +
#     geom_vline(aes(xintercept=mean(age_now, na.rm=T)), colour="#FDBE19", linetype="solid") + 
#    theme(
#     panel.border = element_blank(),  
#          # Remove panel grid lines
#          panel.grid.major = element_blank(),
#          panel.grid.minor = element_blank(),
#          # Remove panel background
#          panel.background = element_blank(),
#          # Add axis line
#          axis.line = element_line(colour = "#BBBEC1")
#   )

```

## Site
```{r Site_blood, warning=FALSE, echo=FALSE, message=FALSE}

sample %>% 
    filter(!is.na(site)) %>%
    ggplot(aes(x=site))+
     xlab("Site") + ylab("Count") + geom_bar(color="black", fill = "#164C71")+  ggtitle("Distrbution of Participant Site Location Among those with a Blood Sample \n")+
   theme(
    panel.border = element_blank(),  
         # Remove panel grid lines
         panel.grid.major = element_blank(),
         panel.grid.minor = element_blank(),
         # Remove panel background
         panel.background = element_blank(),
         # Add axis line
         axis.line = element_line(colour = "#BBBEC1")
  )

```

## Site Defined Sex
```{r Site_Sex_blood, warning=FALSE, echo=FALSE, message=FALSE}

sample %>% 
    filter(!is.na(site_sex)) %>%
    ggplot(aes(x=site_sex))+
     xlab("Sex at Birth") + ylab("Count") + geom_bar(color="black", fill = "#164C71")+  ggtitle("Distrbution of Site Defined Sex Among those with a Blood Sample \n")+
   theme(
    panel.border = element_blank(),  
         # Remove panel grid lines
         panel.grid.major = element_blank(),
         panel.grid.minor = element_blank(),
         # Remove panel background
         panel.background = element_blank(),
         # Add axis line
         axis.line = element_line(colour = "#BBBEC1")
  )

```

## Site Defined Race
```{r Site_Race_blood, warning=FALSE, echo=FALSE, message=FALSE}

sample %>% 
    filter(!is.na(site_race)) %>%
    ggplot(aes(x=site_race))+
     xlab("Site Race") + ylab("Count") + geom_bar(color="black", fill = "#164C71")+  ggtitle("Distrbution of Site Defined Race Among those with a Blood Sample \n")+
   theme(
    panel.border = element_blank(),  
         # Remove panel grid lines
         panel.grid.major = element_blank(),
         panel.grid.minor = element_blank(),
         # Remove panel background
         panel.background = element_blank(),
         # Add axis line
         axis.line = element_line(colour = "#BBBEC1")
  )

```


```{r Race, warning=FALSE, echo=FALSE, message=FALSE}


## Multi-racial

multi_race=0    
for (i in 1:length(demo_tib$Connect_ID)){
  AI=ifelse((demo_tib$D_384191091_D_384191091_D_583826374[[i]]==1 & (demo_tib$D_384191091_D_384191091_D_636411467[[i]]==1 | demo_tib$D_384191091_D_384191091_D_458435048[[i]]==1|
                                               demo_tib$D_384191091_D_384191091_D_706998638[[i]]==1 | demo_tib$D_384191091_D_384191091_D_973565052[[i]]==1 |
                                               demo_tib$D_384191091_D_384191091_D_586825330[[i]]==1 | demo_tib$D_384191091_D_384191091_D_412790539[[i]]==1 |
                                               demo_tib$D_384191091_D_384191091_D_807835037[[i]]==1)), 1, 0)
  As=ifelse((demo_tib$D_384191091_D_384191091_D_636411467[[i]]==1 & (demo_tib$D_384191091_D_384191091_D_583826374[[i]]==1 | demo_tib$D_384191091_D_384191091_D_458435048[[i]]==1|
                                                        demo_tib$D_384191091_D_384191091_D_706998638[[i]]==1 | demo_tib$D_384191091_D_384191091_D_973565052[[i]]==1 |
                                                        demo_tib$D_384191091_D_384191091_D_586825330[[i]]==1 | demo_tib$D_384191091_D_384191091_D_412790539[[i]]==1 |
                                                        demo_tib$D_384191091_D_384191091_D_807835037[[i]]==1)), 1, 0)
  Bl=ifelse((demo_tib$D_384191091_D_384191091_D_458435048[[i]]==1 & (demo_tib$D_384191091_D_384191091_D_583826374[[i]]==1 | demo_tib$D_384191091_D_384191091_D_636411467[[i]]==1|
                                                        demo_tib$D_384191091_D_384191091_D_706998638[[i]]==1 | demo_tib$D_384191091_D_384191091_D_973565052[[i]]==1 |
                                                        demo_tib$D_384191091_D_384191091_D_586825330[[i]]==1 | demo_tib$D_384191091_D_384191091_D_412790539[[i]]==1 |
                                                        demo_tib$D_384191091_D_384191091_D_807835037[[i]]==1)), 1, 0)
  Hs=ifelse((demo_tib$D_384191091_D_384191091_D_706998638[[i]]==1 & (demo_tib$D_384191091_D_384191091_D_583826374[[i]]==1 | demo_tib$D_384191091_D_384191091_D_636411467[[i]]==1|
                                                        demo_tib$D_384191091_D_384191091_D_458435048[[i]]==1 | demo_tib$D_384191091_D_384191091_D_973565052[[i]]==1 |
                                                        demo_tib$D_384191091_D_384191091_D_586825330[[i]]==1 | demo_tib$D_384191091_D_384191091_D_412790539[[i]]==1 |
                                                        demo_tib$D_384191091_D_384191091_D_807835037[[i]]==1)), 1, 0)
  Me=ifelse((demo_tib$D_384191091_D_384191091_D_973565052[[i]]==1 & (demo_tib$D_384191091_D_384191091_D_583826374[[i]]==1 | demo_tib$D_384191091_D_384191091_D_636411467[[i]]==1|
                                                        demo_tib$D_384191091_D_384191091_D_458435048[[i]]==1 | demo_tib$D_384191091_D_384191091_D_706998638[[i]]==1 |
                                                        demo_tib$D_384191091_D_384191091_D_586825330[[i]]==1 | demo_tib$D_384191091_D_384191091_D_412790539[[i]]==1 |
                                                        demo_tib$D_384191091_D_384191091_D_807835037[[i]]==1)), 1, 0)
  Hw=ifelse((demo_tib$D_384191091_D_384191091_D_586825330[[i]]==1 & (demo_tib$D_384191091_D_384191091_D_583826374[[i]]==1 | demo_tib$D_384191091_D_384191091_D_636411467[[i]]==1|
                                                        demo_tib$D_384191091_D_384191091_D_458435048[[i]]==1 | demo_tib$D_384191091_D_384191091_D_706998638[[i]]==1 |
                                                        demo_tib$D_384191091_D_384191091_D_973565052[[i]]==1 | demo_tib$D_384191091_D_384191091_D_412790539[[i]]==1 |
                                                        demo_tib$D_384191091_D_384191091_D_807835037[[i]]==1)), 1, 0)
  Wh=ifelse((demo_tib$D_384191091_D_384191091_D_412790539[[i]]==1 & (demo_tib$D_384191091_D_384191091_D_583826374[[i]]==1 | demo_tib$D_384191091_D_384191091_D_636411467[[i]]==1|
                                                        demo_tib$D_384191091_D_384191091_D_458435048[[i]]==1 | demo_tib$D_384191091_D_384191091_D_706998638[[i]]==1 |
                                                        demo_tib$D_384191091_D_384191091_D_586825330[[i]]==1 | demo_tib$D_384191091_D_384191091_D_973565052[[i]]==1 |
                                                        demo_tib$D_384191091_D_384191091_D_807835037[[i]]==1)), 1, 0)
  Ot=ifelse((demo_tib$D_384191091_D_384191091_D_807835037[[i]]==1 & (demo_tib$D_384191091_D_384191091_D_583826374[[i]]==1 | demo_tib$D_384191091_D_384191091_D_636411467[[i]]==1|
                                                        demo_tib$D_384191091_D_384191091_D_458435048[[i]]==1 | demo_tib$D_384191091_D_384191091_D_706998638[[i]]==1 |
                                                        demo_tib$D_384191091_D_384191091_D_586825330[[i]]==1 | demo_tib$D_384191091_D_384191091_D_973565052[[i]]==1 |
                                                        demo_tib$D_384191091_D_384191091_D_412790539[[i]]==1)), 1, 0)
  multi_race= multi_race + sum(AI+As+Bl+Hs+Me+Hw+Wh+Ot, na.rm=T)

}

#cat("Percentage of multirace participants:", (multi_race/(dim(demo_tib)[1]))*100)
   
   

demo_tib$multi_racial <- c(rep(1, times=multi_race), rep(0, times=(dim(demo_tib)[1]- multi_race)))



## RACE

demo_tib= demo_tib %>%  mutate(race= case_when(multi_racial==1 ~ "Multi-Racial",
                                                     D_384191091_D_384191091_D_583826374==1 ~ "American Indian/Native",
                                                     D_384191091_D_384191091_D_636411467==1 ~ "Asian",
                                                     D_384191091_D_384191091_D_458435048==1 ~ "Black",
                                                     D_384191091_D_384191091_D_706998638==1 ~ "Hispanic",
                                                     D_384191091_D_384191091_D_973565052==1 ~ "Middle Eastern",
                                                     D_384191091_D_384191091_D_586825330==1 ~ "Hawaiian",
                                                     D_384191091_D_384191091_D_412790539==1 ~ "White",
                                                     (D_384191091_D_384191091_D_807835037==1 | !is.na(D_384191091_D_747350323)) ~ "Other",
                                                     D_384191091_D_384191091_D_746038746==1 ~ "Prefer Not to Answer",
                                                     TRUE  ~ "Skipped this question"),
                               sex= case_when(D_407056417=="536341288" ~"Female",
                                              D_407056417=="654207589" ~"Male",
                                              TRUE ~"Intersex or Unknown"))




```


## Participant Defined Sex
```{r Sex_blood, warning=FALSE, echo=FALSE, message=FALSE}

demo_tib %>% 
    filter(!is.na(sex)) %>%
    ggplot(aes(x=sex))+
     xlab("Sex at Birth") + ylab("Count") + geom_bar(color="black", fill = "#164C71")+  ggtitle("Distrbution of Participant Defined Sex Among those with a Blood Sample \n")+
   theme(
    panel.border = element_blank(),  
         # Remove panel grid lines
         panel.grid.major = element_blank(),
         panel.grid.minor = element_blank(),
         # Remove panel background
         panel.background = element_blank(),
         # Add axis line
         axis.line = element_line(colour = "#BBBEC1"),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

```

## Participant Defined  Race
```{r Race_blood, warning=FALSE, echo=FALSE, message=FALSE}

demo_tib %>% 
    filter(!is.na(race)) %>%
    ggplot(aes(x=race))+
     xlab("Race") + ylab("Count") + geom_bar(color="black", fill = "#164C71")+  ggtitle("Distrbution of Participant Defined Race \n Among those with a Blood Sample \n")+
   theme(
    panel.border = element_blank(),  
         # Remove panel grid lines
         panel.grid.major = element_blank(),
         panel.grid.minor = element_blank(),
         # Remove panel background
         panel.background = element_blank(),
         # Add axis line
         axis.line = element_line(colour = "#BBBEC1"),
    axis.text.x = element_text(angle = 60, hjust = 1)
  )

```
